package librarymanagement;

import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Shushank
 */
public class FeesSubmit extends javax.swing.JFrame {
     Connection con;
     PreparedStatement ps;
     ResultSet rs;
     ArrayList al;
     int stuid,seatnum;
     String Name;
    /**
     * Creates new form FeesSubmit
     */
    public FeesSubmit(int num) {
        try{
            al=new ArrayList();
            
//            this.setExtendedState(JFrame.MAXIMIZED_BOTH);
//            this.setSize(Toolkit.getDefaultToolkit().getScreenSize());
            initComponents();
            //JOptionPane.showMessageDialog(this,"First Line of Fees Submit");
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/librarymanagement","root","root");
            tf1.setEditable(false);
            tf2.setEditable(false);
            tf3.setEditable(false);
            if(num<=104){
                //if num is less than 104 it means it is seatNum
               ps=con.prepareStatement("select addstudent.stuid, addstudent.name, bookseat.seatnum from addstudent inner join bookseat on addstudent.stuid = bookseat.stuid and bookseat.seatnum =?");
               ps.setInt(1,num);
               rs= ps.executeQuery();
               if(rs.next()){
                 stuid= rs.getInt(1);
                 Name = rs.getString(2);
                 seatnum= rs.getInt(3);
               }
               else{
                   JOptionPane.showMessageDialog(this,"Data Not Found");
               }
            }
            else{
                ps=con.prepareStatement("select addstudent.stuid, addstudent.name, bookseat.seatnum from addstudent inner join bookseat on addstudent.stuid = bookseat.stuid and addstudent.stuid =?");
               ps.setInt(1,num);
               rs= ps.executeQuery();
               if(rs.next()){
                 stuid= rs.getInt(1);
                 Name = rs.getString(2);
                 seatnum= rs.getInt(3);
               }
               else{
                   JOptionPane.showMessageDialog(this,"Data Not Found");
               }
            }
            tf1.setText(String.valueOf(stuid));
            tf2.setText(Name);
            tf3.setText(String.valueOf(seatnum));
            
        }
        catch(HeadlessException | ClassNotFoundException | SQLException e){
            JOptionPane.showMessageDialog(this, e);
        }
    }

    private FeesSubmit() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tf4 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tf5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Handwriting", 1, 24)); // NOI18N
        jLabel1.setText("Fees Submit");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 27, -1, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        jLabel2.setText("StuId");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        jLabel3.setText("Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 140, -1, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        jLabel4.setText("SeatNo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 180, -1, -1));

        tf1.setBackground(new java.awt.Color(255, 204, 255));
        tf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf1ActionPerformed(evt);
            }
        });
        tf1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf1KeyTyped(evt);
            }
        });
        getContentPane().add(tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 193, 25));

        tf2.setBackground(new java.awt.Color(255, 204, 255));
        tf2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf2KeyTyped(evt);
            }
        });
        getContentPane().add(tf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 193, 25));

        tf3.setBackground(new java.awt.Color(255, 204, 255));
        tf3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf3KeyTyped(evt);
            }
        });
        getContentPane().add(tf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 193, 25));

        jLabel5.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        jLabel5.setText("Submission Date");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 220, -1, -1));

        tf4.setBackground(new java.awt.Color(255, 204, 255));
        tf4.setText("yyyy-MM-dd");
        tf4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf4FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tf4FocusLost(evt);
            }
        });
        tf4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf4ActionPerformed(evt);
            }
        });
        getContentPane().add(tf4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 193, 25));

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Lucida Handwriting", 1, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 110, 40));

        jLabel6.setFont(new java.awt.Font("Lucida Handwriting", 1, 18)); // NOI18N
        jLabel6.setText("Fees");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, 20));

        tf5.setBackground(new java.awt.Color(255, 204, 255));
        tf5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf5KeyTyped(evt);
            }
        });
        getContentPane().add(tf5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 193, 25));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/librarymanagement/Ori.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try{            
            if(tf5.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Please Add Fees");
                
            }
            else if(tf4.getText().equals("yyyy-MM-dd")){
                LocalDate currentDate = LocalDate.now();
                 // Format the date (optional)
                DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd");
                String formattedDate = currentDate.format(formatter);
                boolean flag=true;
                       int fees=Integer.parseInt(tf5.getText());
                        int oriFees=0;
                        ps=con.prepareStatement("select TotalFees from addstudent where stuid = ?");
                        ps.setInt(1,stuid);
                        rs=ps.executeQuery();
                        if(rs.next()){
                            oriFees=rs.getInt(1);
                        }
                        oriFees=oriFees-fees;
                        ps=con.prepareStatement("update addstudent set TotalFees = ? where stuid =? ");
                        ps.setInt(1, oriFees);
                        ps.setInt(2,stuid);
                        int result=ps.executeUpdate();
                        if(result<0)
                            flag=false;
                            
                        ps=con.prepareStatement("insert into feestable values(?,?,?)");
                        ps.setInt(1, stuid);
                        ps.setInt(2,fees);
                        ps.setString(3,formattedDate);
                        int rs=ps.executeUpdate();
                        if(rs<0)
                           flag=false;
                            if(!flag)
                            JOptionPane.showMessageDialog(this,"Unsuccessful");
                           
                            JOptionPane.showMessageDialog(this,"Now Fees is "+oriFees);
                             tf1.setText("");
                            tf2.setText("");
                            tf3.setText("");
                            tf4.setText("");
                            tf5.setText("");
                            tf1.requestFocus();
                                          
            }
            else{
                String date=tf4.getText();
                boolean flag=true;
                SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            // Parse the string to obtain a Date object
                Date date2 = dateFormat.parse(date);
                java.sql.Date sqlDate = new java.sql.Date(date2.getTime());
               
                   
                        int fees=Integer.parseInt(tf5.getText());
                        int oriFees=0;
                        ps=con.prepareStatement("select TotalFees from addstudent where stuid = ?");
                        ps.setInt(1,stuid);
                        rs=ps.executeQuery();
                        if(rs.next()){
                            oriFees=rs.getInt(1);
                        }
                        oriFees=oriFees-fees;
                        ps=con.prepareStatement("update addstudent set TotalFees = ? where stuid =? ");
                        ps.setInt(1, oriFees);
                        ps.setInt(2,stuid);
                        int result=ps.executeUpdate();
                        if(result<0)
                            flag=false;
                            
                        ps=con.prepareStatement("insert into feestable values(?,?,?)");
                        ps.setInt(1, stuid);
                        ps.setInt(2,fees);
                        ps.setDate(3,sqlDate);
                        int rs=ps.executeUpdate();
                        if(rs<0)
                           flag=false;
                            if(!flag)
                            JOptionPane.showMessageDialog(this,"Unsuccessful");
                           
                            JOptionPane.showMessageDialog(this,"Thank You\nNow your Fees is "+oriFees);
                            tf1.setText("");
                            tf2.setText("");
                            tf3.setText("");
                            tf4.setText("");
                            tf5.setText("");
                            tf1.requestFocus();
                           

                    }
                    new FeesSec().setVisible(true);
                    this.dispose();
         }
          
        catch(HeadlessException | NumberFormatException | SQLException | ParseException e){
            JOptionPane.showMessageDialog(this,e);
        }         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tf4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf4ActionPerformed

    private void tf4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf4FocusGained
        if(tf4.getText().equals("yyyy-MM-dd")){
            tf4.setText("");
            tf4.setForeground(new Color(0,0,0));
        }
                                 
    }//GEN-LAST:event_tf4FocusGained

    private void tf4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf4FocusLost
        if(tf4.getText().equals("")){
            tf4.setText("yyyy-MM-dd");
            tf4.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_tf4FocusLost

    private void tf1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf1KeyTyped
if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_tf1KeyTyped

    private void tf2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf2KeyTyped
        char ch = evt.getKeyChar();
        if(!((ch>='a'&&ch<='z')||(ch>='A'&&ch<='Z')||(int)ch==32||(int)ch==8)){
            evt.consume();
        }
    }//GEN-LAST:event_tf2KeyTyped

    private void tf3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf3KeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_tf3KeyTyped

    private void tf5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf5KeyTyped
if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_tf5KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FeesSubmit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FeesSubmit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FeesSubmit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FeesSubmit.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FeesSubmit().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf5;
    // End of variables declaration//GEN-END:variables
}
